org: joebailey26
app: my-first-app
service: calendar
provider:
  name: aws
  timeout: 30
  memorySize: 256
functions:
  index:
    handler: functions-build/calendar.calendar
    events:
      - http:
          path: /
          method: GET
          cors:
            origin: '*'